

const whole = ['Entire', null]
const rooms = ['1 Bedroom', '2 Bedroom', '3 Bedroom', '4 Bedroom', '5 Bedroom']
const type = ['Dome', 'Castle', 'Cottage', 'Hut', 'Igloo', 'Hobbit-Hole', 'Palace', 'Dungeon', 'Apartment', 'Farm', 'Lake House', 'Beach House', 'Hacker House']
const mod = ['in', 'by', 'within 1 mile of', 'within 2 miles of', 'within 5 miles of', 'walking distance to', 'a stone\'s throw away from', 'right by', 'in the heart of', 'in downtown']
const area = [
'Noble Crest Stables',
'Gibb’s Farm',
'Triple Axes Pub',
'Arrowhead Inn',
'Yeomen’s Manor',
'Bootstraps & Buckles Cobbler',
'Dwarf’s Gullet Tavern',
'Hollowvale Village',
'Thunder Hoof Stables',
'Clipper’s County',
'Gresgo’s Pond',
'Hemm’s Tailors',
'Ditch’n’Dagger Tavern',
'Twin Horses Lake Town',
'Boggs Landing',
'Heatherstown Village',
'Trekker’s Square',
'Embris Hollow',
'Zagoroth Mountain Town',
'Padsley Village',
'Sleeping Dragon Inn',
'Ramoth Lye Creek',
'Dragmire Drove',
'Archer’s Ale House',
'Peeker’s Valley',
'Anvil & Flint Blacksmithery',
'Pale Thorn Cove',
'Fang Peak',
'Arc of the Holy Shield Monastery',
'Breggo’s Beard Brewery',
'Golden Stalk Granary',
'Saw and Splinter’s Woodshop',
'Siren’s Shipyard',
'Silver Fin Fishery',
'Addler’s Drove',
'Black Morrow Marshes',
'Shepherd’s Field',
'Honeyclover Meadow',
'Finch & Fox Inn',
'The Warren Pub',
'Fennel & Fallow Bakery',
'Rose & Crown Tavern',
'Knight’s Motte and Bailey',
'White Elk Hall',
'Briar Bridge Village',
'Mighty Hart Furriers',
'Ekhart Bridge',
'The Magpie’s Market',
'Thresh’s Cove',
'Denmarrow Mountains',
'Simple Beasts Watering Hole',
'Lowly Strider Almshouse',
'Miss Plunkerhouse’s Grand Tailors',
'White Lion Halls',
'Thousand Lanterns Inn',
'Wild Hare Country Tavern',
'Laskerville Village',
'Scout’s Towers',
'Golden Longbow Fields',
'Tuckborrow Village',
'Trader’s Turn Plaza',
 'Stoneburrow Town',
'Brather’s Town',
'Stout Dragon Tavern',
'Dueling Swords Blacksmithery',
'The Braided Plait Bakery',
'Mossy Stone Cove',
'Fairy Winds Beach',
'Old Stone Giant Mill',
'Sacred Scroll Holy Monastery',
'King Rothenham Square',
'Brewer’s Bounty Alehouse',
'Oslocrest Town',
'Parsca’s Plaza',
'Old Mayfield Farms',
'Fowler’s Prize Furrers',
'Iron Halberd Smithy',
'Dukes Valley',
'Burrowing Badger Inn',
'Pork Belly’s Butcher Shop',
'Cast Iron Almshouse',
'Three Braided Beards Tavern',
'King’s Own Tailors',
'County Arms Smithy',
'Golden Rise Bakery',
'Spotted Finch Meadows',
'Fairy Sisters Pasture',
'Twin Owls Inn',
'Snow Bard Village',
'DarkVale Valley',
'Tallard’s Orchards',
'Two Moons Cove',
'Star Fin Shipyard',
'White Wind Mill Bakery',
'Troll’s Hand Masons',
'Vatrecastle Village',
'Archer’s Arm Tavern',
'Throne of the Ancient One Temple',
'Swift Axes Woodcutter Shoppe',
'Evenly Yoked Stables',
'Open Hands Almshouse',
'Far Wren Village',
'Stonefell',
'Rustfort',
'Crowband',
'Eaststorm',
'Newshield',
'Mosshall',
'Shroudfalls',
'Bridgevale',
'Baymount',
'Whaledrift',
'Smoothwind',
'Timberdale',
'Bouldermoor',
'Snakehill',
'Glimmercross',
'Silverbreach',
'Rimebourne',
'Knightmoor',
'Rogueguard',
'Brinewatch',
'Timberbrook',
'Lakewich',
'Darkwell',
'Baregulf',
'Fairville',
'Greenfort',
'Magehand',
'Baremeadow',
'Baybourne',
'Sunhaven',
'Oxstrand',
'Beachbell',
'Newborn',
'Snakefell',
'Sandvault',
'Basinfrost',
'Stillshire',
'Crystalgulch',
'Starfalls',
'Duskbarrow',
'Mutestrand',
'Knightbrook',
'Silkmere',
'Fearwatch',
'Southgrave',
'Emberwell',
'Miststall',
'Mightburgh',
'Darkyard',
'Oldford',
'Eldermaw',
'Midshire',
'Stormshore',
'Oxview',
'Fallhall',
'Shadowgrasp',
'Lostford',
'Graybreach',
'Eldershire',
'Bonewatch',
'Knightharbor',
'Shimmermoor',
'Sleetstall',
'Dogbury',
'Millguard',
'Cursegulf',
'Swiftmaw',
'Ghostshield',
'Millfell',
'Roguestrand',
'Cavelight',
'Hollowrock',
'Steammond',
'Elderwall',
'Pineward',
'Dogbarrow',
'Baypoint',
'Blindfair',
'Newmount',
'Clearrun',
'Roseshell',
'Rustrun',
'Purekeep',
'Whaleborn',
'Steepmire',
'Pearlbury',
'Pearlhallow',
'Swanford',
'Dragonhallow',
'Crystalreach',
'Muteminster',
'Ravenbourne',
'Wintermoor',
'Smoothland',
'Southcrest',
'Eagleacre',
'Purehorn',
'Falsewood',
'Stormcall',
'Emberfort',
'Amberfall',
'Dusthold',
'Everview',
'Basinmaw',
'Steelcairn',
'Nevergulch',
'Houndscar',
'Ironpost',
'Honeyville',
'Clearbreak',
'Greenport',
'Roguebell',
'Goldguard',
'Summermount',
'Farreach',
'Ebonholde',
'Honeyhelm',
'Grimfell',
'Blindlight',
'Spiritvale',
'Ghostgulch',
'Oxacre',
'Mosswick',
'Glimmerfield',
'Curseglen',
'Duststall',
'Boulderborn',
'Fairbarrow',
'Eaglebreak',
'Cliffville',
'Highgrasp',
'Oxholde',
'Cloudyard',
'Highbarrow',
'Honeyreach',
'Dewguard',
'Frostshell',
'Deerfrost',
'Mudpass',
'Faybrook',
'Winterbury',
'Shroudmere',
'Castlemire',
'Whitsummit',
'Littlerun',
'Moonhorn',
'Rimescar',
'Frostgarde',
'Oakenfield',
'Grimburn',
'Lagoonpeak',
'Gloomhold',
'Earthrock',
'Freywich',
'Ghosthorn',
'Slypost',
'Dogbreak',
'Grimecrest',
'Smallhallow',
'Bellfall',
'Oxholde',
'Spirithost',
'Dragonyard',
'Bearwind',
'Stormpoint',
'Sandgarde',
'Steamshire',
'Direborn',
'Heartbarrow',
'Cliffview',
'Brittlegrave',
'Bareshire',
'Dawngate',
'Swampcairn',
'Fearguard',
'Lightmount',
'Deeprest',
'Deerfield',
'Edgegulch',
'Brittleburn',
'Lakechill',
'Nightshear',
'Swiftshear',
'Pearlfront',
'Starlight',
'Wildeside',
'Everside',
'Roguebrook',
'Deadtide',
'Boulderharbor',
'Smallgate',
'Sunbrook',
'Steepmoor',
'Knightfield',
'Mistreach',
'Westdenn',
'Beargate',
'Timbertide',
'Winterbarrow',
'Whitbury',
'Pearlminster',
'Dawnhost',
'Silkmire',
'Dragonbay',
'Steelborough',
'Glimmerbell',
'Mosshallow',
'Millhaven',
'Shadowyard'
]

let hipster = 'Diy Flannel Normcore Umami Meh Coloring Book Fanny Pack Bushwick Tote Bag Tumeric Gochujang Authentic Chicharrones Semiotics Yr Letterpress Flexitarian Stumptown Synth Blog Ugh Unicorn Dreamcatcher Slow-Carb Typewriter Franzen Slow-Carb Synth Gochujang Bushwick Freegan Bitters Etsy Twee Plaid Chia Health Goth Butcher Trust Fund Lumbersexual Food Truck Subway Tile Umami Mixtape Pop-Up Authentic La Croix Cold-Pressed Tumeric Coloring Book Master Cleanse Chartreuse Keytar Taiyaki Try-Hard Sustainable Mumblecore Slow-Carb Tofu Woke Sustainable Cray Wayfarers Selvage Adaptogen Shoreditch Snackwave Tbh Synth Meh Gluten-Free Yuccie 3 Wolf Moon Asymmetrical Raclette Celiac Iphone Shoreditch ShamanTrust Fund Post-Ironic Williamsburg Jean Shorts Hashtag Franzen Dreamcatcher Cold-Pressed Scenester Occupy Roof Party Tattooed La Croix Vegan Tbh Swag +1 Irony Austin Dreamcatcher Skateboard Distillery Cray Meditation Palo Santo Tacos Crucifix Iphone Artisan Forage Bespoke Tilde Meh Jean Shorts Authentic Pop-Up Artisan Jean Shorts Sartorial Pork Belly Selfies Mustache Tumblr Retro Meditation Vhs Polaroid Normcore Cliche Tousled Swag Selvage Fanny Pack Venmo WolfMan Bun Viral Squid Pour-Over Pabst Salvia Mustache Prism Craft Beer Cardigan Bicycle Rights Copper Mug Pug Pinterest Hoodie Stumptown Letterpress Fanny Pack Pabst Pitchfork Unicorn Fam Pok Pok 90s Affogato Artisan Trust Fund Chia Subway Tile Pop-Up Chicharrones Iphone 8-Bit Jianbing Xoxo Kogi Actually Flannel Try-Hard Tattooed Sustainable Squid Ramps Knausgaard Celiac Vice Pickled Polaroid Actually Ethical Leggings Sartorial Tattooed Marfa Migas Bespoke Yuccie Adaptogen Artisan Irony Bitters Tacos Organic Sriracha Biodiesel Intelligentsia Pug Scenester Live-Edge Truffaut Paleo Pop-Up Typewriter Chillwave Cronut Godard Fam Banjo Portland Crucifix Tote Bag 90sDrinking Vinegar Coloring Book Blue Bottle Bushwick Diy Flannel Af Woke Franzen Tofu Unicorn Hella Freegan 8-Bit Gastropub 8-Bit Messenger Bag Man Braid Pork Belly Kickstarter Drinking Vinegar Hella Wolf Bushwick Schlitz Everyday Carry Single-Origin Coffee 90s Gentrify +1 Microdosing Dreamcatcher 90s Kogi Whatever Palo Santo Pok Pok Celiac Helvetica Air Plant Wayfarers Cred Lumbersexual Mixtape Freegan Xoxo Crucifix Hell of Roof Party Waistcoat Squid Cliche Health Goth Blue Bottle Knausgaard Shaman Iceland Semiotics Gastropub Cold-Pressed Actually Selfies Edison Bulb Viral Irony Sustainable Franzen Before They Sold Out Brunch Irony Quinoa Squid Hella Mumblecore Vegan Neutra Bespoke Affogato Cold-Pressed Adaptogen Mustache Quinoa Taxidermy Mlkshk Next Level Readymade Flexitarian Green Juice Pug Bespoke Woke Cold-Pressed Retro Sriracha Tilde Biodiesel Live-Edge Fanny Pack Knausgaard Coloring Book Plaid Marfa Paleo Celiac Church-Key Snackwave Aesthetic Hexagon Sartorial Pug Taiyaki Pitchfork Craft Beer Blue Bottle Fashion Axe Offal Shabby Chic Humblebrag Tbh Glossier You Probably Havent Heard of Them Four Loko Green Juice 3 Wolf Moon Selvage Blue Bottle Typewriter Beard Tattooed Celiac Raw Denim Cred Viral Trust Fund Copper Mug Truffaut Blog Viral Craft Beer Brunch Retro Chia Next Level Pop-Up Master Cleanse Meditation Fam Ugh Put a Bird on It Roof Party Umami Paleo Meggings Before They Sold Out Sustainable Post-Ironic Hashtag Forage Shoreditch Whatever Art Party Beard La Croix Mumblecore Shabby Chic Salvia Typewriter Plaid 8-Bit Shabby Chic Keytar Taxidermy Butcher Distillery Yr Scenester Pitchfork Meggings Flexitarian Wayfarers Marfa Pitchfork Artisan Fashion Axe Occupy Farm-To-Table Kogi Gochujang Irony Chillwave Jean Shorts Polaroid Diy Cold-Pressed Vaporware Sustainable Narwhal Knausgaard Tote Bag Heirloom Pork Belly Adaptogen Pug Ennui Drinking Vinegar Hell Of Gentrify Cloud Bread Ramps Put a Bird on It Forage Aesthetic Street Art Artisan Marfa Yuccie Gastropub Small Batch Cray Prism Viral Humblebrag Bitters Neutra Viral Pop-Up Fingerstache Chia Celiac Affogato Vexillologist Before They Sold Out Fixie Blog Artisan Iphone Shabby Chic Raclette Unicorn Bespoke Pug Celiac Ugh Hell of Occupy Salvia Seitan 8-Bit Fashion Axe Plaid Farm-To-Table Cold-Pressed Skateboard Post-Ironic Keffiyeh Thundercats Enamel Pin Meggings Flexitarian Vegan Semiotics Coloring Book Fashion Axe Occupy Pbr&b Waistcoat Venmo Pickled Lo-Fi Yolo Hexagon Cronut Hoodie 90s Next Level Helvetica Pour-Over Literally Hashtag Cliche Bitters Put a Bird on It Flannel Tumeric Leggings Salvia Vinyl Chillwave Gentrify Fashion Axe Cliche Coloring Book Live-Edge Chicharrones Mumblecore Deep V Microdosing Drinking Vinegar Retro 3 Wolf Moon Yolo Man Braid Taxidermy Gluten-Free Paleo Blue Bottle Butcher Fashion Axe Adaptogen Tumeric Affogato Small Batch Keffiyeh Fingerstache Vexillologist Succulents Etsy Letterpress Actually Hella Shabby Chic Blue Bottle Umami Freegan Pabst Messenger Bag Drinking Vinegar Mumblecore Tumeric Sustainable Vape La Croix Live-Edge Typewriter Small Batch Quinoa Trust Fund Shoreditch Pitchfork Adaptogen Shaman Raw Denim Plaid Thundercats Fixie Wolf Yuccie Listicle Banh Mi Deep V Post-Ironic Viral Craft Beer Meggings Raclette Neutra Affogato Gochujang Before They Sold Out Literally Green Juice Pbr&b Man Braid Lomo Deep V Bespoke Offal Messenger Bag Vinyl Actually Four Dollar Toast Polaroid Artisan Tattooed Messenger Bag Shoreditch Scenester Live-Edge Jianbing Man Bun Next Level Sustainable Fingerstache Before They Sold Out Gochujang Kitsch Gluten-Free Neutra Man Braid Raclette Live-Edge Butcher Single-Origin Coffee Tilde Literally Hoodie Banh Mi Hexagon Etsy Freegan Echo Park Letterpress Enamel Pin Yuccie Hammock Everyday Carry 8-Bit Pok Pok Kale Chips Swag Venmo Diy Wayfarers Brooklyn Lomo Master Cleanse Pork Belly Pickled Raclette Food Truck Selfies Williamsburg Sustainable Put a Bird on It Meh Pbr&b Pok Pok Twee Kogi Pour-Over Blog Tofu Adaptogen Shabby Chic Kale Chips Mumblecore 90s Fixie Mumblecore Leggings Vape Hexagon Etsy Vhs Diy Green Juice Hammock Authentic Jean Shorts Pok Pok Vice Roof Party Brooklyn Crucifix Gochujang Wolf Cliche Lyft Art Party Pour-Over Chia Kitsch Adaptogen Vexillologist Photo Booth Meditation Shabby Chic Truffaut Fashion Axe Activated Charcoal Cold-Pressed Tousled Tilde Fanny Pack Chartreuse Fam Cloud Bread Man Braid Vice Green Juice Hell of Mumblecore Enamel Pin Asymmetrical Raclette Franzen Humblebrag Trust Fund Vape Keffiyeh Lo-Fi Blog Craft Beer Irony Synth Fingerstache Subway Tile Sartorial Selfies Jianbing Wolf Vegan 90s Keffiyeh Mustache Portland Cornhole Iceland Banjo Chambray Pork Belly Cliche Succulents Cardigan Organic Bitters Jean Shorts Mixtape Migas Kinfolk Try-Hard Wayfarers Keffiyeh Tbh Portland Fingerstache Roof Party Snackwave Vhs Small Batch Blog 8-Bit Microdosing Keytar Heirloom You Probably Havent Heard of Them Mixtape Meh Deep V Vape Vegan Readymade Mlkshk Fingerstache Vinyl Photo Booth Narwhal Venmo Marfa Bitters Organic Put a Bird on It Biodiesel Truffaut Distillery Intelligentsia Paleo Banjo Semiotics Tattooed 8-Bit Kinfolk Artisan Art Party Yr Narwhal Mixtape Locavore Ugh Copper Mug Hell of Photo Booth Slow-Carb Meggings Trust Fund Subway Tile You Probably Havent Heard of Them Farm-To-Table Air Plant Tattooed Biodiesel Fingerstache Locavore Cronut Diy Fam Vinyl Woke Lyft Intelligentsia Paleo Mumblecore Kombucha Small Batch Flannel Prism Celiac Squid Thundercats 90s Forage Hoodie Taiyaki Kogi Master Cleanse You Probably Havent Heard of Them Photo Booth Snackwave Shaman Direct Trade Post-Ironic Cloud Bread Hot Chicken Cray Edison Bulb Authentic Vinyl Man Braid Af Bicycle Rights Food Truck Freegan Health Goth Microdosing Kickstarter Man Bun Four Dollar Toast Kitsch Neutra Intelligentsia Typewriter Godard Shoreditch Next Level Kogi Tattooed Before They Sold Out Xoxo Drinking Vinegar Poke Unicorn Air Plant Copper Mug Sartorial Typewriter Mumblecore Hashtag Meh Seitan Marfa Semiotics Pork Belly Gluten-Free Gochujang Normcore Biodiesel Chillwave Cray Selvage Irony Gastropub Organic Hella Vinyl Gentrify Semiotics Umami Microdosing Hoodie Raw Denim Brunch Chicharrones Green Juice Wayfarers Beard Tote Bag Hot Chicken Snackwave Skateboard Shaman 90s Yr Church-Key Plaid Live-Edge Vhs Woke Hexagon Semiotics Venmo Palo Santo Roof Party Put a Bird on It Lo-Fi Coloring Book Succulents Brooklyn Biodiesel Gentrify Vaporware Mumblecore Banh Mi 3 Wolf Moon Copper Mug Irony Pbr&b Etsy Yolo Squid Cardigan Hammock Four Loko Twee Meh Beard Pok Pok Flexitarian Poke Tofu Cred Cloud Bread Pinterest Kale Chips Godard Polaroid Artisan Food Truck Venmo Helvetica Pitchfork Irony Pinterest Intelligentsia Artisan Godard Williamsburg Try-Hard Street Art Schlitz Adaptogen Umami Raw Denim Swag Green Juice Retro Mumblecore Synth Salvia Hella Chambray Kitsch Organic Man Bun Bespoke Put a Bird on It Gastropub Helvetica Gochujang Cronut Salvia 8-Bit Flannel Locavore Fam Pour-Over Waistcoat Diy Quinoa Twee Crucifix Asymmetrical Pour-Over Yr Flexitarian Coloring Book Photo Booth Stumptown Poutine Disrupt Pok Pok Vegan Authentic Pbr&b Celiac Yolo Vinyl Hell of Shaman Jianbing Vape Irony Art Party Vape Tote Bag Helvetica Xoxo Aesthetic Hammock Vhs Franzen Vinyl Wolf Bitters Retro Kinfolk Flexitarian Activated Charcoal Ennui Vexillologist Tofu Raclette Food Truck Pug La Croix Vexillologist Tousled Keffiyeh 90s Palo Santo Subway Tile Polaroid Plaid Pop-Up Gastropub Narwhal Activated Charcoal Hell of Poke Plaid Kinfolk Church-Key Gentrify Hexagon Hot Chicken Mumblecore Godard Try-Hard Unicorn Tbh Craft Beer Jianbing Ennui Kogi Quinoa Put a Bird on It Brooklyn Next Level Small Batch Live-Edge Ramps Scenester Synth Semiotics Diy 8-Bit Before They Sold Out Umami Pitchfork Synth Bicycle Rights Roof Party Migas Tattooed Gastropub Plaid Portland Church-Key Meditation Shoreditch Pour-Over Mumblecore Intelligentsia Vape Vice Photo Booth Freegan Pickled Typewriter Chartreuse Xoxo Forage Sartorial Gluten-Free Kogi Roof Party Whatever Activated Charcoal Live-Edge Vaporware Shoreditch Distillery Narwhal Umami Mlkshk Slow-Carb Deep V Viral Live-Edge Shaman Gastropub Diy Flannel Gastropub Raw Denim Freegan Post-Ironic Marfa Crucifix Offal Sustainable Woke Green Juice Asymmetrical Hammock Chambray Knausgaard Fam Hexagon Kinfolk Beard Pickled Scenester Retro Ennui Swag Actually Hella Four Dollar Toast Intelligentsia Listicle Tumeric Prism La Croix Narwhal Vexillologist Twee Chia Venmo Single-Origin Coffee Hoodie Fashion Axe Listicle Tousled Hella Forage Ennui Pop-Up Letterpress Flannel Scenester Aesthetic Pabst Four Loko Helvetica Pbr&b Chambray Waistcoat Schlitz Cardigan Everyday Carry Poke Salvia Readymade Prism Palo Santo Cornhole Bushwick Cold-Pressed Semiotics Portland Coloring Book Forage Gentrify Schlitz Blog Hoodie Poutine Mixtape Wolf Selvage Skateboard Knausgaard Palo Santo Authentic Drinking Vinegar Ethical Venmo Bushwick Crucifix Quinoa Wayfarers Bicycle Rights Hexagon Tousled Vice Sustainable Lomo Cardigan Heirloom Vexillologist Chartreuse Shoreditch Iphone Mlkshk Tattooed Wayfarers Sartorial Austin Fanny Pack Flexitarian Tattooed Meditation Iceland Lyft Distillery Cronut Shaman Street Art Microdosing Snackwave Food Truck Keffiyeh Gluten-Free Shaman Health Goth Iphone 90s Shabby Chic Migas You Probably Havent Heard of Them Prism Lyft Locavore Semiotics Thundercats Whatever Sartorial Typewriter Kinfolk Woke Kickstarter Dreamcatcher Slow-Carb Food Truck Lumbersexual Activated Charcoal Austin Taxidermy Jianbing Vape Aesthetic Cronut Skateboard Tattooed Sustainable Venmo Bespoke Polaroid Lyft Fanny Pack Put a Bird on It Everyday Carry Helvetica Actually Kitsch Diy Aesthetic Selfies Snackwave Trust Fund Single-Origin Coffee Heirloom Thundercats Retro Vape Succulents Chicharrones Pitchfork Ugh Waistcoat Celiac Actually Air Plant Jean Shorts Messenger Bag Health Goth Tilde Bushwick Organic Poke Letterpress Hexagon Helvetica Vegan Craft Beer Franzen Trust Fund Normcore Venmo Master Cleanse 8-Bit Tumblr Cornhole Hot Chicken Hashtag Humblebrag Raclette Chicharrones Lo-Fi Roof Party Ennui Forage Edison Bulb Coloring Book Xoxo Normcore Selfies Flexitarian Chambray Tattooed Tilde Crucifix Seitan Cardigan Umami Pop-Up Pop-Up Ramps Mlkshk Vhs Celiac Letterpress Bushwick Everyday Carry Deep V Plaid Live-Edge Kale Chips Pork Belly Viral Cardigan Etsy Deep V Sriracha Cloud Bread Heirloom Snackwave Small Batch Poke Try-Hard Gochujang Chillwave Pabst Meggings Synth Echo Park Celiac Crucifix Snackwave Brooklyn Iceland Gastropub Bitters Shoreditch Yuccie Readymade Chia Distillery Four Dollar Toast Celiac Schlitz 8-Bit Echo Park Artisan Gluten-Free Cray Palo Santo Master Cleanse Vice Crucifix Williamsburg Venmo Beard Brooklyn Blog 3 Wolf Moon Godard Tote Bag Kale Chips Pug Affogato Post-Ironic Craft Beer Occupy Yolo Sustainable Succulents Health Goth Gluten-Free Pinterest Messenger Bag Af Tumblr Ugh Art Party Diy Blog Farm-To-Table Quinoa Chicharrones Bitters Skateboard Squid Four Loko Lomo Pickled Fixie Pok Pok Direct Trade Humblebrag Kickstarter You Probably Havent Heard of Them Flannel Vegan Celiac Lomo Hashtag Tacos Yr Fanny Pack Everyday Carry Kombucha Sriracha Butcher Godard Vaporware Irony Twee Mustache Fixie Beard Live-Edge Try-Hard Subway Tile Seitan Cloud Bread Kogi Blog Farm-To-Table Brunch Drinking Vinegar Chia Retro Jianbing Yr Bespoke Tumblr Activated Charcoal Swag Bitters Vice Scenester Godard Man Braid Banh Mi Af Food Truck Thundercats Pinterest Pork Belly Single-Origin Coffee Stumptown Chartreuse Paleo Meditation Cold-Pressed Meh Tilde Seitan Ramps Af Raw Denim Dreamcatcher Bespoke Artisan Semiotics Blog Swag Man Braid Coloring Book Jean Shorts Umami Lo-Fi Single-Origin Coffee Echo Park Humblebrag Cronut Poutine Shabby Chic Listicle Bitters Raw Denim Beard Butcher Distillery Literally Kombucha Polaroid Sustainable Asymmetrical Bushwick Literally Farm-To-Table Schlitz Tumeric Af Pitchfork Jean Shorts Iceland Shaman Shoreditch Food Truck Farm-To-Table Selvage Dreamcatcher Iceland Cloud Bread Meditation Hexagon Iphone Irony Glossier Occupy Live-Edge Celiac Meggings Selvage Poutine Cloud Bread Ugh Church-Key Food Truck Small Batch 8-Bit Wolf Chambray Irony Leggings Whatever Chicharrones Polaroid Succulents Hexagon Keytar Thundercats Food Truck Fam Butcher Man Bun Shaman Swag Put a Bird on It Pitchfork Tilde Lo-Fi Mumblecore Messenger Bag Aesthetic Xoxo Asymmetrical Art Party Jianbing Wolf Franzen Tumeric Bespoke Irony 8-Bit Forage Hell of Shaman Hammock Flannel Slow-Carb Venmo Kinfolk Man Braid Etsy Skateboard Banjo Waistcoat Yolo Normcore Godard Polaroid Man Bun Etsy Paleo Cloud Bread Mixtape Mumblecore Migas Blog Vinyl Shaman Godard Photo Booth Asymmetrical Prism Art Party Plaid Sustainable Disrupt Thundercats Authentic Mixtape Four Loko Biodiesel Semiotics Umami Mixtape Viral Try-Hard Fanny Pack Banjo Gastropub Church-Key Echo Park Messenger Bag 3 Wolf Moon Pbr&b Poke Vape Pabst Man Braid Kickstarter Vexillologist Tbh Lomo Keffiyeh Four Loko Farm-To-Table Gochujang Meditation Paleo +1 Marfa Post-Ironic Sustainable Humblebrag Neutra Green Juice Asymmetrical Unicorn Deep V Occupy Normcore Xoxo Polaroid Knausgaard Aesthetic Venmo Four Dollar Toast Mumblecore Intelligentsia Ramps Godard Taiyaki Dreamcatcher Activated Charcoal Poke Palo Santo Adaptogen Irony Tousled Viral Sartorial Cray Meh Wolf Woke Four Loko Portland Chambray Marfa Ugh Flexitarian Fixie Single-Origin Coffee Vaporware Shoreditch Umami Pinterest Bicycle Rights Skateboard Fingerstache Tofu Poutine Art Party Cliche Tacos Vegan Shoreditch La Croix Semiotics Tilde Cronut Offal Chartreuse Snackwave Kickstarter Chambray Iphone Prism 3 Wolf Moon Humblebrag Cloud Bread Normcore Authentic Salvia Post-Ironic Banjo Lo-Fi Post-Ironic Yolo Meh Put a Bird on It 90s Offal Poutine Chartreuse Intelligentsia Occupy Trust Fund Cold-Pressed Schlitz Irony Marfa Lyft Williamsburg Wolf Meh Pour-Over Freegan Swag Copper Mug +1 Pinterest Selvage Deep V Raw Denim Af Subway Tile Xoxo Synth Truffaut Shabby Chic Thundercats Humblebrag Edison Bulb Everyday Carry Small Batch Raclette Jianbing Retro Tumeric Tattooed Flannel Polaroid Truffaut Brunch Cred Semiotics Vinyl Seitan Raclette Pop-Up Green Juice Pickled Artisan Lomo Ethical Occupy Flexitarian Organic Flannel Tofu Meggings La Croix Cold-Pressed Chia Tumblr Shoreditch Master Cleanse Butcher Iceland You Probably Havent Heard of Them Raw Denim Lyft Cornhole Cloud Bread Blog Shoreditch Drinking Vinegar Schlitz Small Batch Shaman Affogato Art Party Palo Santo Williamsburg Retro Godard Vaporware Fashion Axe Tofu Pok Pok Meh Neutra Pour-Over Gastropub Fashion Axe Celiac Plaid Coloring Book Put a Bird on It Palo Santo Gentrify Forage Intelligentsia Prism Cray Swag Blog 90s Mustache Tote Bag Af Kitsch La Croix Seitan Gentrify Occupy Copper Mug Mlkshk Pbr&b Humblebrag Health Goth Skateboard Freegan Plaid Tilde Tbh Cornhole Affogato Gastropub Twee Jianbing Yr Selvage Woke Coloring Book Crucifix Hella Normcore Small Batch Lomo Crucifix Disrupt Gluten-Free Kitsch Hammock Asymmetrical Roof Party Cloud Bread Fingerstache Shoreditch Scenester Selfies Gentrify Slow-Carb Umami Shoreditch Scenester Letterpress Cronut Single-Origin Coffee Disrupt Raw Denim Normcore Cliche Vegan Etsy Stumptown Freegan Artisan Vaporware Single-Origin Coffee Kickstarter Hot Chicken Meh Tattooed Asymmetrical Franzen Poutine Lumbersexual Etsy Ramps Marfa Ennui Art Party Migas Pitchfork Pug Craft Beer Narwhal Enamel Pin Kinfolk Blue Bottle You Probably Havent Heard of Them Keytar Vexillologist Pabst Mumblecore Locavore Tbh Irony Raclette Letterpress Pinterest You Probably Havent Heard of Them Live-Edge Iceland Health Goth Mixtape Brooklyn Pop-Up Tumblr Before They Sold Out Tumblr Paleo Disrupt Banh Mi Taxidermy Chicharrones Iceland Cold-Pressed Master Cleanse Migas Sustainable Pour-Over Vinyl Celiac Food Truck Austin Kinfolk Hexagon Man Bun Paleo Xoxo Vinyl Pabst Air Plant Pour-Over Green Juice Jianbing Asymmetrical Cornhole Enamel Pin Poke Street Art Pabst Flexitarian Master Cleanse Jianbing Chia Tumblr Iphone Helvetica Farm-To-Table Plaid Squid Fanny Pack Gastropub Keffiyeh Vegan Before They Sold Out Glossier Snackwave Hella Hot Chicken Tumblr Keffiyeh Artisan Gluten-Free Paleo Tbh Palo Santo Cornhole Meggings Hell of Green Juice Live-Edge Sustainable Diy Four Dollar Toast Typewriter Salvia Health Goth Ramps Brunch Man Braid Fam Forage Sriracha Tote Bag Bitters Cred Beard Sriracha Man Braid Diy Jean Shorts Skateboard Normcore Asymmetrical Umami Raw Denim Paleo Street Art Subway Tile Shabby Chic Vinyl Plaid Thundercats Diy Squid Chia Migas Raclette Poutine Tofu Shoreditch Disrupt Tacos Copper Mug Meggings Synth Glossier Ramps Iphone Drinking Vinegar Trust Fund Vaporware Man Braid Franzen Raclette Put a Bird on It Asymmetrical Post-Ironic Mlkshk Fam Af Pabst Chambray Edison Bulb Shaman Chia Forage Pabst Art Party Disrupt Small Batch Cred Iphone Salvia Truffaut Cloud Bread Street Art Locavore Helvetica 3 Wolf Moon Post-Ironic Williamsburg Leggings Migas Prism Four Loko Pickled Air Plant Williamsburg Af Palo Santo Roof Party Master Cleanse Shoreditch Scenester Selfies Hoodie Wayfarers Franzen Messenger Bag Slow-Carb Kale Chips Paleo Bicycle Rights Copper Mug Raclette Asymmetrical Put a Bird on It Iceland Health Goth Sustainable Raw Denim Tilde Messenger Bag Gluten-Free Brunch Pabst Neutra Marfa Keytar Listicle Xoxo Poke Cardigan Hell of Dreamcatcher Offal Locavore Scenester Subway Tile Lomo Readymade Gastropub Meggings Activated Charcoal Skateboard Raw Denim Irony Air Plant Distillery Etsy Vinyl Cloud Bread Street Art Yr Kale Chips Distillery Intelligentsia +1 Squid Brunch Biodiesel Sartorial Subway Tile Coloring Book Knausgaard Vice Taxidermy Schlitz Trust Fund Fanny Pack Everyday Carry Organic Pour-Over Franzen Wolf Photo Booth Kitsch Echo Park Heirloom Bicycle Rights Portland Skateboard Gochujang Chartreuse Mumblecore Drinking Vinegar Polaroid Gluten-Free Small Batch Poutine Vhs Enamel Pin Helvetica Humblebrag You Probably Havent Heard of Them Cloud Bread Asymmetrical Vaporware Raw Denim Yuccie Snackwave Tofu Ethical Mumblecore Tilde Artisan Paleo Semiotics Bitters Subway Tile Fanny Pack Prism Gochujang Pok Pok Shaman Before They Sold Out Coloring Book Activated Charcoal Bitters Umami Biodiesel Pickled Irony Selfies Lyft Sriracha Hoodie +1 Aesthetic Irony Pinterest Kogi Readymade Vinyl Coloring Book Kinfolk Actually Gentrify Art Party Sustainable Pour-Over Bespoke Skateboard Kale Chips Vaporware Actually Kombucha Whatever Farm-To-Table Lyft Tumblr +1 Blue Bottle Hot Chicken Sriracha Biodiesel Tattooed Church-Key Xoxo Activated Charcoal Hexagon Tofu Pug Green Juice Godard Readymade Banh Mi Franzen Quinoa Fixie Blog Authentic Bicycle Rights Distillery Roof Party Kale Chips Venmo Meh Tousled Pinterest Craft Beer Schlitz Vexillologist Tattooed Drinking Vinegar Pbr&b Taiyaki Adaptogen Hot Chicken Diy You Probably Havent Heard of Them Austin Vinyl Poke Live-Edge Hashtag Post-Ironic Lomo Vegan Taxidermy Jean Shorts Cred Cloud Bread Hoodie Fanny Pack Artisan 90s Waistcoat Chia Crucifix Narwhal Prism Authentic Chicharrones Pok Pok Helvetica Pop-Up Microdosing Twee Lyft Fingerstache Green Juice Marfa Scenester La Croix Butcher Twee La Croix Hoodie Vhs 90s Church-Key Mumblecore Wolf Biodiesel Kinfolk Master Cleanse Wolf Authentic Pabst Synth Venmo Poutine Ennui Narwhal Blog Pug Shaman Seitan Tumblr Banjo Man Braid Cardigan Ugh Vaporware Meggings Raclette Everyday Carry Vice Prism Next Level Af Lo-Fi Affogato Pickled Copper Mug Brunch Distillery Listicle Four Loko Keffiyeh Organic Heirloom Master Cleanse Keffiyeh Paleo Plaid Hell of Vaporware Semiotics Four Loko Sartorial Gentrify Viral Tote Bag Mlkshk Paleo Snackwave Tofu Keffiyeh Blue Bottle Air Plant Gluten-Free Hot Chicken Slow-Carb Ramps You Probably Havent Heard of Them Mumblecore Taiyaki +1 Woke Jean Shorts Pinterest Biodiesel Organic Shoreditch Health Goth Vhs Tbh Whatever Retro Hammock Cray Art Party Tumblr Church-Key Unicorn Man Bun Cronut Lumbersexual Vegan Dreamcatcher Cornhole Ramps Raw Denim You Probably Havent Heard of Them Pinterest Street Art Pitchfork Aesthetic Succulents Bicycle Rights Poutine Keffiyeh Skateboard Paleo Actually Hot Chicken Gochujang Sartorial Poke Pbr&b Ugh Pug Mixtape Portland 3 Wolf Moon Blog Letterpress Man Bun Slow-Carb Actually Typewriter Raclette Truffaut Palo Santo Knausgaard Pour-Over Bespoke Next Level Keffiyeh Biodiesel Scenester Before They Sold Out Single-Origin Coffee Kale Chips Venmo Portland Etsy Pop-Up Cronut Tousled Chicharrones Polaroid Meditation Try-Hard Shabby Chic Cliche Slow-Carb Diy 8-Bit Retro Pork Belly Kogi Williamsburg Coloring Book Man Braid Four Loko Gentrify Vice Pork Belly Chia Hell of Etsy Offal Hexagon Sartorial Fam Hot Chicken Direct Trade Crucifix Kogi 8-Bit Forage Meggings Ramps Skateboard Banh Mi Cornhole Pitchfork Neutra Selvage Aesthetic Mumblecore Intelligentsia Banh Mi Yuccie Schlitz Offal Venmo Dreamcatcher Hashtag Pinterest Hella Cliche Lyft Disrupt Adaptogen Meh Selfies La Croix Jianbing Irony Marfa Chambray Enamel Pin Iphone +1 Master Cleanse Woke Art Party Yr Cornhole Tumeric Brunch Try-Hard Kogi Vexillologist Tumeric Seitan Skateboard Diy Umami Kale Chips Tbh Sartorial Pour-Over Succulents Iceland Coloring Book Poke +1 Master Cleanse Brooklyn Hella Jianbing Woke Williamsburg Bicycle Rights Raclette Banjo Slow-Carb Polaroid Pug Before They Sold Out Man Braid Venmo Try-Hard Tumeric Biodiesel Bicycle Rights Salvia Vexillologist Subway Tile Semiotics Pitchfork Unicorn Photo Booth Ugh Butcher Fam Bushwick Hammock Migas Cloud Bread Austin Poutine Master Cleanse Biodiesel Fixie Cloud Bread Hoodie Kale Chips Live-Edge Pabst Neutra Sriracha Offal Iceland Meggings Vice Vegan Whatever Messenger Bag Offal Hella Selfies La Croix Venmo Brooklyn Whatever Unicorn Godard Taxidermy Blog Church-Key Pbr&b Man Bun Xoxo Pug Venmo Lo-Fi Cloud Bread Intelligentsia Tacos +1 Beard Biodiesel Gastropub Listicle Pop-Up Pok Pok Wolf Asymmetrical Messenger Bag Man Bun Venmo Man Braid Cliche Four Loko Slow-Carb Etsy Everyday Carry Hoodie Succulents Farm-To-Table Hot Chicken Authentic Air Plant Paleo Fashion Axe Chillwave Shoreditch Small Batch Post-Ironic Affogato Lo-Fi Prism Keffiyeh Cardigan Live-Edge Enamel Pin Edison Bulb Drinking Vinegar Craft Beer Polaroid Meggings Irony Prism Vexillologist Squid Unicorn Messenger Bag Brunch Iphone Williamsburg Jean Shorts Pabst Aesthetic Shabby Chic La Croix Helvetica You Probably Havent Heard of Them Tote Bag Chia Master Cleanse Messenger Bag La Croix Polaroid Hella Vaporware Vegan Dreamcatcher Intelligentsia You Probably Havent Heard of Them Pbr&b Ramps Brunch Pug Farm-To-Table Affogato Drinking Vinegar Chartreuse Cardigan Post-Ironic Mlkshk Master Cleanse Austin Cold-Pressed Poutine Stumptown Vape Four Loko Twee Mustache Crucifix Post-Ironic Banjo Roof Party Pitchfork Squid Sustainable Fingerstache Gentrify Waistcoat Chillwave Artisan Twee Vegan Snackwave Jianbing Crucifix Occupy Live-Edge Gastropub Ennui Vegan Four Loko Microdosing Cold-Pressed Poutine Jianbing Letterpress Direct Trade Plaid Cornhole Gentrify 8-Bit Vice You Probably Havent Heard of Them Ugh Drinking Vinegar Mlkshk Williamsburg Cray Put a Bird on It Austin Intelligentsia Xoxo Gochujang Craft Beer Readymade Franzen Pok Pok Before They Sold Out Palo Santo Master Cleanse Semiotics Butcher 8-Bit Banjo Jianbing Bitters'

let dataGen = function (whole, rooms, type, mod, area, string) {
  let data = []
  for(var i = 1; i < 10; i++) {
    let wholeRand = whole[Math.floor(Math.random() * whole.length)]
    let roomsRand = rooms[Math.floor(Math.random() * rooms.length)]
    let typeRand = type[Math.floor(Math.random() * type.length)]
    let modRand = mod[Math.floor(Math.random() * mod.length)]
    let areaRand = area[Math.floor(Math.random() * area.length)]
    let hipsterArr = string.split(' ')
    let hipsterStr = ''
    let randHipLen = Math.ceil(Math.random() * 4)
    for(var i = 0; i <= randHipLen; i++) {
      let hipsterRand = hipsterArr[Math.floor(Math.random() * hipsterArr.length)]
      hipsterStr = hipsterStr + hipsterRand
    }
    let inMod = null
    if (wholeRand) {
      let inMod = 'in'
    }
    let name = wholeRand + roomsRand + inMod + typeRand + modRand + areaRand + hipsterStr;

    let listing = {_id: i, name: name}

    console.log(wholeRand)
  }

}

dataGen(whole, rooms, type, mod, area, hipster)


